version: '2.0'
services:

  registration-service:
    container_name: registration-service
    image: raf43/registration-service:0.0.1-SNAPSHOT
    expose:
    - 10000
    ports:
    - 10000:10000
    network_mode: host

  account-service:
    container_name: account-service
    image: raf43/account-service:0.0.1-SNAPSHOT
    expose:
    - 10001
    ports:
    - 10001:10001
    depends_on:
    - registration-service
    network_mode: host

  report-service:
    container_name: report-service
    image: raf43/report-service:0.0.1-SNAPSHOT
    expose:
    - 10002
    ports:
    - 10002:10002
    depends_on:
    - registration-service
    - account-service
    network_mode: host

  api-gateway:
    container_name: api-gateway
    image: raf43/api-gateway:0.0.1-SNAPSHOT
    expose:
    - 12345
    ports:
    - 80:12345
    depends_on:
    - registration-service
    network_mode: host
