server:
  port: 10002

spring:
  application:
    name: report-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}