server:
  port: 18888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # local repo
          uri: file:///home/raf/IdeaProjects/spring-cloud-microservice-sample-config
          # remote repo
          #uri: https://github.com/rtatol/spring-cloud-microservice-sample-config.git